version: "3.9"
services:
  raspberry:
    restart: always  
    build: ./raspberry
    privileged: true
    volumes:
      - /usr/bin/vcgencmd:/usr/bin/vcgencmd
      - /dev/mem:/dev/mem
      - /usr/lib/aarch64-linux-gnu/libvchiq_arm.so.0:/usr/lib/aarch64-linux-gnu/libvchiq_arm.so.0
      - /usr/lib/aarch64-linux-gnu/libvcos.so.0:/usr/lib/aarch64-linux-gnu/libvcos.so.0
    depends_on:
      - db
    ports:
      - "8081:8081"
    env_file:
      - ./.env.app.dev
  db:
    restart: always
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env.db.dev

volumes:
  postgres_data:
#    external: true