version: "3.9"
services:
  raspberry:
    build: ./raspberry
    privileged: true
    volumes:
      - /raspberry/main.py:/main.py
      - /usr/bin/vcgencmd:/usr/bin/vcgencmd
      - /dev/mem:/dev/mem
      - /usr/lib/aarch64-linux-gnu/libvchiq_arm.so.0:/usr/lib/aarch64-linux-gnu/libvchiq_arm.so.0
      - /usr/lib/aarch64-linux-gnu/libvcos.so.0:/usr/lib/aarch64-linux-gnu/libvcos.so.0
    depends_on:
      - db
    env_file:
      - ./.env.app.dev
  telegram:
    build: ./telegram
    ports:
      - "8081:8081"
    volumes:
      - /raspberry/main.py:/main.py
    depends_on:
      - db
    env_file:
      - ./.env.app.dev
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5436:5432"
    expose:
      - 5432
    env_file:
      - ./.env.db.dev

volumes:
  postgres_data: